<?php
define('CARBRAND','CODE_CAR_BRAND');
define('CARMODEL','CODE_CAR_MODEL');
define('CARBUILDYEAR','CODE_CAR_BUILDYEAR');
define('CARBUILDMONTH','CODE_CAR_BUILDMONTH');
define('CAREXECUTION','CODE_CAR_EXECUTION');
define('CARDOORS','CODE_CAR_DOORS');
define('CARGEARBOX','CODE_CAR_GEARBOX');
define('CARDRIVETYPE','CODE_CAR_DRIVETYPE');
define('CARENGINE','CODE_CAR_ENGINETYPE');
define('POSTALCODE','CODE_POSTALCODE');
define('COUNTRY','CODE_COUNTRY');
define('LANGUAGE','CODE_LANGUAGE');
define('SEARCHREQUEST','SEARCH_REQUEST');
define('SEARCHARTICLE','SEARCH_ARTICLE');
define('USER','USER_USER');
define('USERCONTACT','USER_CONTACT');
define('USERREPLY','USER_REPLY');
define('CARCATEGORY','CODE_CAR_CATEGORY');
define('CARSUBCATEGORY','CODE_CAR_SUBCATEGORY');



?>